### ISSUE TITLE
How to use generated sample extension

### ISSUE THREAD

**Issue by bloomsa** [jupyter-server/extension-cookiecutter#13]
## Description
I ran through the setup process with cookiecutter to generate my sample extension but I'm not understanding how to test it within a running jupyter server. My (naive) understanding was that this extension just adds a `/ping` endpoint to the server that responds with a 200 and 'pong', but I'm either misunderstanding the code, or missing something. 

The server extension does appear to load correctly judging from the logs below
![Screen Shot 2022-09-06 at 10 30 03 PM](https://user-images.githubusercontent.com/20909250/188782692-1e82a872-a853-4f07-adf8-bd124fc0ba12.png)

## Reproduce

1. run `cookiecutter https://github.com/jupyter-server/extension-cookiecutter` 
2. complete prompts and navigate into the new directory
3. run `pip install .`
4. run `jupyter server`

## Expected behavior
I expected to be able to `curl http://localhost:8888/myextension/ping` but that returned a 404 instead of "pong"

## Context

- Operating System and version:
- Browser and version:
- Jupyter Server version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by blink1073** [comment]
Hi @bloomsa, the endpoint is currently http://localhost:8888/ping, but I agree we should put it under http://localhost:8888/myextension/ping to promote best practices.  Additionally, the endpoint is marked as authenticated, so a naive `curl` will give you a 403 error.

**Comment by bloomsa** [comment]
thanks @blink1073! `curl`-ing `localhost:8888/ping` with my jupyter server token as query param worked! I swear I tried that route before raising this question from a different terminal window but I must not have.. 🤦 in any case, I appreciate the quick response. 

If you wanted to make an issue to resolve that, you could assign me and I'll give it a shot 🙂
