### ISSUE TITLE
The ping url should be namespaced

### ISSUE THREAD

**Issue by blink1073** [jupyter-server/extension-cookiecutter#14]
Currently we are using a top level url (`/ping`) in the recipe.  It should be namespaced with the extension name, to promote best practices.

**Comment by blink1073** [comment]
@bloomsa GitHub won't let me assign this to you, but feel free to take it.  :smile:

**Comment by bloomsa** [comment]
This issue can be closed, right? @blink1073

**Comment by blink1073** [comment]
Yep!
