### ISSUE TITLE
Add test suite infrastructure

### ISSUE THREAD

**Issue by blink1073** [jupyter-server/extension-cookiecutter#4]
We should use `jupyter_server.pytest_plugin` and create a simple test file.

For an example see, 

https://github.com/jupyter-server/jupyter_server/blob/main/examples/simple/conftest.py
https://github.com/jupyter-server/jupyter_server/blob/main/examples/simple/tests/test_handlers.py

We would need to add a test dependency on `jupyter_server[test]` in `pyproject.toml`, e.g.

```toml
[project.optional-dependencies]
tests = [
  'pytest',
  'jupyter_server[test]`
]
```

**Comment by 3coins** [comment]
@blink1073 
We should also add the linting support here. Can you assign this to me.

**Comment by blink1073** [comment]
Done!
